version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: passwd
    ports:
      - '5432:5432'
    networks:
      - docker-net
    volumes:
      - db-data:/var/lib/postgresql/data
  php:
    build: ./php
    ports:
      - '80:80'
      - '9000:9000'
    environment:
      - SERVERNAME=php7.localdomain
      - SERVERALIAS=
    volumes:
      - ./html:/var/www/html
    links:
      - db
    networks:
      - docker-net
  adminer:
    image: adminer
    restart: always
    ports:
      - '8000:8080'
    networks:
      - docker-net

networks:
  docker-net:
    driver: bridge

volumes:
  db-data:
    driver: local
